networks:
  oupharmacy_network:
    driver: bridge

services:
  frontend:
    build:
      context: ./oupharmacyapp
    networks: 
      - oupharmacy_network
    ports: # Vite port: 5173 => 3000:80 Nginx
      - "3000:80" 
    expose: 
      - 5173

  backend:
    build:
      context: ./OUPharmacyManagementApp
    networks:
      - oupharmacy_network
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    expose: 
      - 8000

  db:
    image: mysql:8.0
    networks: 
      - oupharmacy_network
    env_file: 
      - ./.env
    container_name: mysql_container
    ports:
      - "3307:3306"
    expose: 
      - 3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: